name: Preprocess Car Evaluation Dataset

on:
  push:
    branches:
      - main  # trigger saat push ke main branch
  workflow_dispatch:  # juga bisa dijalankan manual dari GitHub UI

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
          persist-credentials: true
          fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.0'  # sesuaikan versi python kamu

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn  # tambahkan library lain jika perlu

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_RamaAdjiPrasetyo.py \
          --input raw_dataset_car_evaluation.csv \
          --output preprocessing/preprocessed_data/

    - name: Setup Git for pushing
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Update preprocessed dataset" || echo "No changes to commit"

    - name: Push changes
      run: git push origin main
